//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/ProtoDefine.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ProtoDefine")]
    public enum ProtoDefine
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_Connect", Value=1001)]
      REQ_Connect = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_Login", Value=1002)]
      REQ_Login = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQ_Register", Value=1003)]
      REQ_Register = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_Connect", Value=1001)]
      RES_Connect = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_Login", Value=1002)]
      RES_Login = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RES_Register", Value=1003)]
      RES_Register = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IND_Broadcast", Value=101)]
      IND_Broadcast = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COM_Build", Value=201)]
      COM_Build = 201
    }
  
}